### PR TITLE
Pod objects py3fixes

### PR DESCRIPTION
**Pull request by axeltanner**
Support the output of additional data related to Pod objects, namely pod.hostip, pod.internaip and pod.services via sysprint;
Some smaller fixes, cleanup, update of inline documentation.

### CODE REVIEW

**Comment by axeltanner** [comment]
Forgot the linting step ... will update after that

**Comment by axeltanner** [comment]
Added the changes coming from linting

**Review by araujof — APPROVED** [review]
LGTM

**Comment by araujof** [comment]
Thanks for this PR!

**Pull request merged**
